### ISSUE TITLE
[bug] 出现同一时间多个相同课程

### ISSUE THREAD

**Issue by INFO-studio** [DL444/cqu-schedule#10]
当订阅课表链接时，小米手机经常（ipados也偶发）出现同一时间点两三个相同课程的情况，引出通知栏提醒（一节课能提醒二三十回且不能单独关闭该日历的提醒），然后瞬间消失。

**Comment by DL444** [comment]
我们猜测问题的原因是 iCalendar 订阅返回的事件唯一 ID 未满足 [RFC 5545](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.4.7) 中的持久性要求。该标准要求同一逻辑事件在整个生命周期中使用同一个唯一 ID, 即使多次请求也是如此：

> This property defines the **persistent**, globally unique identifier for the calendar component.

原有的实现未满足这一要求，导致客户端对未发生变化的事件也执行了移除后重新添加的操作，进而造成时序问题引发的重复展示与重复提醒。

我们基于这一猜测尝试解决了问题并已部署。若问题得到解决，则课表展示应当在下次客户端刷新订阅时自行恢复正常。如刷新后未自动恢复，可尝试手动从客户端移除日历订阅，再重新添加。若重新添加后仍有问题，请重新打开此单并回复。

此外，我们还发现部分用户因为教务平台侧的问题导致个别课程有重复。此问题与反馈无关。我们另行实现了除重机制，以规避该问题。

感谢你的反馈与一贯支持。
