### ISSUE TITLE
[bug] 在考试日历中更改description，添加座位号

### ISSUE THREAD

**Issue by INFO-studio** [DL444/cqu-schedule#13]
![WechatIMG1](https://github.com/DL444/cqu-schedule/assets/49604095/1804a666-da0d-4eec-b895-c026755f8fb4)
可能由于教务网更新，导致原有方法失效

**Comment by INFO-studio** [comment]
（或者可能是outlook本身的问题，但是能否在考试description中添加座位号呢

**Comment by DL444** [comment]
Description 内容问题应该是客户端与日历服务的兼容性问题，我们没有返回这样的数据。你可以通过在浏览器中直接访问订阅地址来验证。
