### ISSUE TITLE
0.0

### ISSUE THREAD

**Issue by ShowMaker4343** [DL444/cqu-schedule#15]
取消订阅 只需要在设置里删了就行了嘛ios

**Comment by DL444** [comment]
在设置中删除订阅会从系统日历中移除课程安排。如果你最初使用日历文件添加日程，那么这就足够了。

如果你最初使用自动更新的日历订阅，那么服务还会继续留存你的登录信息，建议你前往[取消订阅](https://schedule.dl444.net/delete-subscription)页面删除留存的登录信息。

**Comment by ShowMaker4343** [comment]
我在这个页面把订阅取消了 但是日历中还是有课表 这样他还会保存我的信息吗

**Comment by DL444** [comment]
在服务页面上取消订阅后，我们便不会再存储你的登录信息。此前创建的订阅地址将返回空，因此你的日历客户端下次刷新日历时，便应当清理掉原有的日程。

我们无法确定你日历客户端的刷新频率。可以在系统设置里操作移除，以避免等待。

**Comment by ShowMaker4343** [comment]
okok thx
