### ISSUE TITLE
课程库似乎已更新？需要修复

### ISSUE THREAD

**Issue by EtMemor** [DL444/cqu-schedule#5]

**Comment by DL444** [comment]
基础诊断日志显示课表已经在三天左右前更新了。如果你现在还是没能获取到新学期的课表，可以首先尝试重新保存课表文件或重新创建订阅，再将新文件或订阅重新导入到你使用的日历客户端。

如果操作后还有问题，并希望授权我们进一步排查，可以选择将你的学号发送到服务[关于页](https://schedule.dl444.net/about)中列出的电子邮箱中，以便我们针对你的具体情况进行作出诊断。为了避免你的登录信息泄露，请不要在 GitHub Issue 中直接提供你的学号，也不要在任何技术支持途径提供你的登录密码。

自毕业后，本人可投入在监控与维护本服务上的精力持续减少，对于教务系统变更的消息也不再灵通了。因此，服务的很多问题本人并不能及时发现。本服务至今还能工作，都已经是超乎本人想象的。故在此感谢你的一贯支持。

**Comment by EtMemor** [comment]
今日查看日历发现课程已更新！感谢学长一直以来对此项目的付出╰(*°▽°*)╯

**Comment by DL444** [comment]
感谢你的反馈与支持。
