### ISSUE TITLE
服务存在问题，暂时无法创建订阅 

### ISSUE THREAD

**Issue by Yangminyu2002** [DL444/cqu-schedule#7]

**Comment by DL444** [comment]
经排查，我们发现学校教务系统于近期更新了查询课表的接口，并下线了原有接口，导致本服务失效。我们将在最近几天内尽快适配新的接口以恢复服务，敬请耐心等待。

感谢你的反馈。

**Comment by DL444** [comment]
问题已解决，现在可再次尝试创建日历订阅或保存日历文件，预期可成功完成操作。如果你已有订阅，则订阅中的课表已集中更新，你的日历客户端下一次从本服务拉取最新日程时，将能够获取到最新的课程数据。如果仍有问题，可重新打开本单并回复。

自毕业后，本人可投入在监控与维护本服务上的精力持续减少，对于教务系统变更的消息也不再灵通了。正是有广大用户的积极反馈，本服务才能持续运行到今天。在此再次感谢你的反馈与一贯支持。

**Comment by Yangminyu2002** [comment]
感谢学长对此项目的无私付出
